name: Parse Go Target
description: Extract OS and architecture from Go target (GOOS/GOARCH format)

inputs:
  target:
    description: 'Go target (e.g., linux/amd64, darwin/arm64, windows/amd64)'
    required: true

outputs:
  os:
    description: 'Operating system (linux, darwin, windows)'
    value: ${{ steps.parse.outputs.os }}
  arch:
    description: 'Architecture (amd64, arm64, 386)'
    value: ${{ steps.parse.outputs.arch }}
  extension:
    description: 'Binary extension (empty for unix, .exe for windows)'
    value: ${{ steps.parse.outputs.extension }}
  archive_ext:
    description: 'Archive extension (.tar.gz for unix, .zip for windows)'
    value: ${{ steps.parse.outputs.archive_ext }}

runs:
  using: composite
  steps:
    - name: Parse target
      id: parse
      shell: bash
      run: |
        TARGET="${{ inputs.target }}"

        # Extract OS (first segment before /)
        OS=$(echo "$TARGET" | cut -d'/' -f1)
        echo "os=$OS" >> $GITHUB_OUTPUT

        # Extract architecture (second segment after /)
        ARCH=$(echo "$TARGET" | cut -d'/' -f2)
        echo "arch=$ARCH" >> $GITHUB_OUTPUT

        # Determine extension and archive type based on OS
        if [[ "$OS" == "windows" ]]; then
          EXT=".exe"
          ARCHIVE_EXT=".zip"
        else
          EXT=""
          ARCHIVE_EXT=".tar.gz"
        fi

        echo "extension=$EXT" >> $GITHUB_OUTPUT
        echo "archive_ext=$ARCHIVE_EXT" >> $GITHUB_OUTPUT

        echo "Parsed target: $TARGET"
        echo "  OS: $OS"
        echo "  Arch: $ARCH"
        echo "  Extension: $EXT"
        echo "  Archive: $ARCHIVE_EXT"
