'*.{json,md,toml,yaml,yml}':
  - task format:prettier --
  - task eslint -- --fix
'*.sh':
  - task shlint_py -- --fix
'*.ps1':
  - task pwshlint_py -- --fix
'*.py':
  - task ruff -- format
  - task pylint --
'*.go':
  - task gofmt -- -s -w
  - task lint:go --
