language: go
go_import_path: github.com/templ-project/go
os:
  - linux
  - osx
  - windows
go:
  - 1.13.x
  - 1.14.x
  # - master
env:
  - MODE=app
  - MODE=mod
before_install:
  # https://docs.travis-ci.com/user/private-dependencies#api-token
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - if [[ "$TRAVIS_OS_NAME" = "windows" ]]; then choco install -y make; fi
  - if [[ "$TRAVIS_OS_NAME" = "windows" ]]; then powershell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew install make; fi
before_script:
  - make init MODE=$MODE
  - make configure IN_TRAVIS=1
scripts:
  # - set -e
  - bash .scripts/pre-commit.sh --all
  - if [[ $MODE == 'app' ]]; then make run;
    if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then make run-binary BUILD_OS=darwin;
    else make run-binary BUILD_OS=$TRAVIS_OS_NAME;
    fi;
    else make test;
    fi
  - pwd
  - ls .
  - if [[ $TRAVIS_GO_VERSION == '1.14.x' && $TRAVIS_OS_NAME == 'linux' && $MODE == 'mod' ]]; then make docs;
    sonar-scanner; fi
notifications:
  email:
    recipients:
      - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: "templ-project"
    token:
      secure: "WlxoMMZGNpv/IQCqBXNLJClQkL2rseP8mclRRJh4N60bfhhsS58xwyh/KHUjpDN+7zZG/bP/v1L/1CDU7loLnsQPB2f8UeNecukaYx12dRixkKm2WiWXbQHDweZdFpDq/F5dqmbCsDC+LTmaBmhlddJCafXgXM8pVEXYAHZx6A+YluTDAOPE1MMEZlgpjB32sLnMFPiSeW2Ov9WtoTigIG2jpvoBXKJztcTXdn8QdKoxK+19nkReA3UxKHhajMt/xo9+85sqtRXyIumuk0x6iP0256SyjidOY/joQiD9GmmJLPILkWjEH/I6q0Z4eHutiGDwdZ2PCnmcF+cQB2qPssnl+JxHXQcKeFp05aa7GSDGyJezLCPbbX0c1tZZmHP/qKuwFyIK8QRbkwy9+7A5a2sY+YQOqZI8UO5kBmI9uEKF32ofIu/Nnz1BWobHcytWRclK34Cdd1MGFLRBA34j9TpiyuSIGG6bDxei+QVm80QF9MpX86kJm+Z9VoSL0VJZMs17osy1nF1xTBKlrEaOjA/BVRRzYoYvxF8XUFUd76FB5GrcGwNJD5V8C6G6Mn/ihF2SyQlOQkl3aAmuqY8pJIIFQLGhT1DD1p9UjB+h4TTlmq30lbMi9PPgQSzKihIm6/JVBLcoyuQZW4hNPKmYq6fa7/S2CfPMFi4pLwjVcDQ="
