language: go
os:
  - linux
  # - osx
  - windows
go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - master
sudo: false
env:
  - GO111MODULE=on
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install -y make; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then powershell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'; fi
before_script:
  - make configure
scripts:
  - make build
  - make build BUILD_OS=windows
# after_script:
#   - test $TRAVIS_NODE_VERSION == '12' && sonar-scanner
notifications:
  email:
    recipients:
      - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
# addons:
#   sonarcloud:
#     organization: "organisation"
#     token:
#       secure: "secure"

